spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtauthentication
    username: postgres
    password: SentinelDatabasePassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: false